CREATE DATABASE DATATRNSFORMRER;

USE DATATRNSFORMRER;

CREATE TABLE CUSTOMER(
CUSTOMERID INT PRIMARY KEY,
FRISTNAME VARCHAR (20),
LASTNAME VARCHAR (20),
EMAIL VARCHAR (30),
REGISTRATIONDATE DATE 
);

INSERT INTO CUSTOMER (CUSTOMERID, FRISTNAME, LASTNAME, EMAIL, REGISTRATIONDATE)
VALUES
(1, 'RAHUL', 'PATEL', 'RAHUL@GMAIL.COM  ', '2024-01-10'),
(2, 'PRIYA', 'SHAH', 'PRIYA@GMAIL.COM', '2024-01-12'),
(3, 'AMIT', 'VERMA', 'AMIT@GMAIL.COM', '2024-01-15'),
(4, 'NEHA', 'MEHTA', 'NEHA@GMAIL.COM', '2024-01-18');


CREATE TABLE ORDERED(
ORDERID INT PRIMARY KEY,
CUSTOMERID INT,
ORDERDATE DATE,
TOTALAMOUNT DECIMAL,
FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMER(CUSTOMERID)
);

INSERT INTO ORDERED (ORDERID, CUSTOMERID, ORDERDATE, TOTALAMOUNT)
VALUES
(101, 1, '2024-02-01', 2500),
(102, 2, '2024-02-03', 1800),
(103, 1, '2024-02-05', 3200),
(104, 3, '2024-02-07', 1500);


CREATE TABLE EMPLOYEES(
 EMPLOYEESID INT PRIMARY KEY,
FRISTNAME VARCHAR (20),
LASTNAME VARCHAR (20),
DEPARMANT VARCHAR (20),
HIREDATE DATE,
SALARY INT
);

INSERT INTO EMPLOYEES (EMPLOYEESID, FRISTNAME, LASTNAME, DEPARMANT, HIREDATE, SALARY)
VALUES
(1, 'SURESH', 'KUMAR', 'SALES', '2022-05-10', 30000),
(2, 'RINA', 'JOSHI', 'HR', '2021-08-15', 35000),
(3, 'MAHESH', 'PATEL', 'IT', '2023-01-20', 45000),
(4, 'ANITA', 'SHARMA', 'FINANCE', '2020-11-05', 40000);

-- 1

SELECT *
FROM CUSTOMER C
INNER JOIN ORDERED O
ON C.CUSTOMERID = O.CUSTOMERID;

-- 2

SELECT C.CUSTOMERID,C.FRISTNAME,C.LASTNAME,O.ORDERID,O.TOTALAMOUNT
FROM CUSTOMER C
LEFT JOIN ORDERED O
ON C.CUSTOMERID = O.CUSTOMERID; 

-- 3

SELECT O.ORDERID,
C.FRISTNAME,
C.LASTNAME,
C.CUSTOMERID,
C.REGISTRATIONDATE
FROM ORDERED O
RIGHT JOIN CUSTOMER C
ON C.CUSTOMERID = O.CUSTOMERID;

-- 4
 
SELECT *
FROM CUSTOMER C 
JOIN  ORDERED O
ON C.CUSTOMERID = O.CUSTOMERID;

-- 5

SELECT *  
FROM ORDERED
WHERE TOTALAMOUNT > (
	SELECT AVG(TOTALAMOUNT)
	FROM ORDERED
);


-- 6

SELECT EMPLOYEESID  
FROM EMPLOYEES
WHERE SALARY > (
	SELECT AVG(SALARY)
	FROM EMPLOYEES
);

-- 7
SELECT ORDERID,
EXTRACT(YEAR FROM ORDERDATE) AS OREDREDYEAR,
EXTRACT(MONTH FROM ORDERDATE) AS OREDREDMONTH
FROM ORDERED;

-- 8

SELECT ORDERID,
 DATEDIFF(CURDATE(),ORDERDATE)AS NEWDATE
 FROM ORDERED;

-- 9

SELECT ORDERID,
 DATE_FORMAT(ORDERDATE, "%d/%m/%Y")
 AS NEW_FOAMTE
 FROM ORDERED;

-- 10

SELECT 
CUSTOMERID,
CONCAT(FRISTNAME, ' ' ,LASTNAME) AS FULLNAME
FROM CUSTOMER;

-- 11
SELECT 
EMPLOYEESID ,
FRISTNAME,
REPLACE(FRISTNAME,'SURESH','RAJ')
FROM EMPLOYEES;

-- 12
SELECT 
EMPLOYEESID ,
LOWER(FRISTNAME)
FROM EMPLOYEES;

-- 13
SELECT 
CUSTOMERID ,
TRIM(EMAIL) AS 'RIGHT EMAIL'
FROM CUSTOMER;

-- 14
SELECT
ORDERID,
ORDERDATE,
TOTALAMOUNT,
SUM(TOTALAMOUNT) OVER (
    ORDER BY ORDERDATE
) AS RUNNING_TOTAL
FROM ORDERED;

-- 15
SELECT
ORDERID,
TOTALAMOUNT,
RANK() OVER (
ORDER BY
CASE
	WHEN TOTALAMOUNT>=3200 THEN 1
    WHEN TOTALAMOUNT>=2500 THEN 2
    WHEN TOTALAMOUNT>=1500 THEN 3
    ELSE 4
    END )AS RANKORDER
FROM ORDERED;

-- 16
SELECT
ORDERID,
TOTALAMOUNT,
CASE
	WHEN TOTALAMOUNT>=3000 THEN (3000 - 0.10)
    WHEN TOTALAMOUNT>=2000 THEN (2000 - 0.7)
    WHEN TOTALAMOUNT>=1000 THEN (1000 - 0.2)
    ELSE 'NO DISCOUNT'
    END AS DISCOUNT
FROM ORDERED;


-- 17

SELECT EMPLOYEESID , SALARY,FRISTNAME,
	CASE
		WHEN SALARY >= 60000 THEN 'HIGH'
		WHEN SALARY BETWEEN 40000 AND 59999 THEN 'MEDIYAM'
        ELSE 'LOW'
END AS EMPLOYEES_SALARY
FROM EMPLOYEES;